
services:
  frontend:
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile
    ports:
      - "19000:19000"
      - "19001:19001"
    volumes:
      - ./frontend:/app
    tty: true
    stdin_open: true
    command: npm start
